### PR TITLE
pharmaPCSAFT and combining rules

### PR DESCRIPTION
**Pull request by longemen3000**
this PR adds a new EoS and a new feature.
- `pharmaPCSAFT`: a PCSAFT variant, with temperature-dependent kij and and special handling for water if passed as `"water08"`.
- Combining rules for association: `AssocOptions` has a new keyword: `combining`, with options `sparse_nocombining` (default for all SAFT/CPA), `dense_nocombining` and `elliott` (default for `pharmaPCSAFT`).

addresses #75

### CODE REVIEW

**Comment by longemen3000** [comment]
@pw0908 is the name ok?

**Comment by longemen3000** [comment]
there was an error when calling for the temperature dependent sigma of water so the better results are just the work of the new combining rules

**Comment by pw0908** [comment]
Looking at the code, it seems Delta assoc is using the wrong kappa? There shouldn't be a sigma in there. The units of kappa in pharmaPCSAFT are in angstrom

**Comment by pw0908** [comment]
Ignore that, I realise the reason we can't replicate the activity is most-likely related to the association combining rules; Im good to merge for now

**Pull request merged**
