### PR TITLE
bounded RR and ASS in TP flash

### PR DESCRIPTION
**Pull request by gustavochm**
Hey guys,

I hope you are doing ok. I made some updates to the TP flash. I updated the RR solution procedure, to be bounded between 0 and 1 and  included acceleration into the SS solution procedure.

I also noticed the volume function was not using the analytical procedure for cubic EoS so I also changed that.

Another question that I have, is that when using cubic EoS for some reason by default the interaction parameters are obtained from the PC-SAFT database. Is that intentional?

Regards,
Gustavo

### CODE REVIEW

**Comment by longemen3000** [comment]
SGTM  in my opinion, @pw0908 ?

**Comment by pw0908** [comment]
Sorry for not replying soon enough; been working on some other stuff. Everything here looked great to me! Do we need to add new tests?

**Comment by longemen3000** [comment]
Just some coverage ones, nothing too fancy

**Comment by gustavochm** [comment]
I don't think so, the flash solvers are basically the same functions. The changed just made the RR solution procedure a bit more robust and the acceleration can save some iterations.

One thing though, regardless the interaction parameters for the cubic EoS. By default Clapeyron uses the kij from PC-SAFT, is that intentional?

**Comment by pw0908** [comment]
Completely accidental; we'll fix that

**Pull request merged**
